"""
Liveliness-AI — FastAPI Backend Entry Point
============================================
Step 1: Backend infrastructure (no AI processing yet).

This file bootstraps the FastAPI application, registers all routers,
and configures global settings (CORS, metadata, lifespan events).

Run the server:
    uvicorn main:app --reload --host 0.0.0.0 --port 8000

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs       ← Swagger UI
    http://localhost:8000/redoc      ← ReDoc
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routes.analyze import router as analyze_router
from app.api.video_routes import router as video_router
from app.api.image_routes import router as image_router
from app.api.audio_routes import router as audio_router


# ---------------------------------------------------------------------------
# Lifespan — runs at startup/shutdown
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Startup: load the DeepFakeV1Module singleton once into GPU/CPU memory
    and call model.eval() globally.  All subsequent requests share this
    single instance — no per-request loading overhead.
    """
    import torch
    from app.ai_engine import model_singleton

    device = (
        "cuda"  if torch.cuda.is_available()
        else "mps" if (hasattr(torch.backends, "mps")
                       and torch.backends.mps.is_available())
        else "cpu"
    )
    model_singleton.load_model(device=device)
    yield
    # Shutdown: nothing to clean up (model lives in process memory)


# ---------------------------------------------------------------------------
# Application factory
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Liveliness-AI",
    description=(
        "Multimodal deepfake detection API. "
        "Accepts image, video, or audio files and returns an authenticity "
        "score, risk classification, and explanation."
    ),
    version="0.2.0",
    lifespan=lifespan,
)

from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------

# Allow all origins during development; tighten this in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------

# All /analyze logic lives in routes/analyze.py
app.include_router(analyze_router, prefix="/analyze", tags=["Analysis"])
app.include_router(video_router,  prefix="/detect",  tags=["Deepfake Detection"])
app.include_router(image_router,  prefix="/detect",  tags=["Deepfake Detection"])
app.include_router(audio_router,  prefix="/detect",  tags=["Deepfake Detection"])

# ---------------------------------------------------------------------------
# Health-check (optional but useful for infra monitoring)
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Health"])
async def health_check():
    """Quick liveness probe — returns 200 if the server is up."""
    return {"status": "ok", "service": "liveliness-ai"}