"""
Liveliness-AI — FastAPI Backend Entry Point
============================================
Step 1: Backend infrastructure (no AI processing yet).

This file bootstraps the FastAPI application, registers all routers,
and configures global settings (CORS, metadata, lifespan events).

Run the server:
    uvicorn main:app --reload --host 0.0.0.0 --port 8000

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs       ← Swagger UI
    http://localhost:8000/redoc      ← ReDoc
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routes.analyze import router as analyze_router

# ---------------------------------------------------------------------------
# Application factory
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Liveliness-AI",
    description=(
        "Multimodal deepfake detection API. "
        "Accepts image, video, or audio files and returns an authenticity "
        "score, risk classification, and explanation."
    ),
    version="0.1.0",  # Step 1 — infrastructure only
)

# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------

# Allow all origins during development; tighten this in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------

# All /analyze logic lives in routes/analyze.py
app.include_router(analyze_router, prefix="/analyze", tags=["Analysis"])


# ---------------------------------------------------------------------------
# Health-check (optional but useful for infra monitoring)
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Health"])
async def health_check():
    """Quick liveness probe — returns 200 if the server is up."""
    return {"status": "ok", "service": "liveliness-ai"}